# services:
#   postgres:
#     image: postgres:15
#     container_name: webhookhub-postgres
#     environment:
#       POSTGRES_USER: webhookhub
#       POSTGRES_PASSWORD: webhookhub
#       POSTGRES_DB: webhookhub
#     ports:
#       - "5432:5432"
#     volumes:
#       - pg_data:/var/lib/postgresql/data

#   zookeeper:
#     image: confluentinc/cp-zookeeper:7.5.0
#     container_name: webhookhub-zookeeper
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#     ports:
#       - "2181:2181"

#   kafka:
#     image: confluentinc/cp-kafka:7.5.0
#     container_name: webhookhub-kafka
#     depends_on:
#       zookeeper:
#         condition: service_started
#     ports:
#       - "9092:9092"
#       - "29092:29092"
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

#       KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
#       KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#       KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#   redis:
#     image: redis:7
#     container_name: webhookhub-redis
#     ports:
#       - "6379:6379"

#   api:
#     build:
#       context: ./api
#     container_name: webhookhub-api
#     env_file:
#       - .env
#     depends_on:
#       postgres:
#         condition: service_started
#       kafka:
#         condition: service_started
#       redis:
#         condition: service_started
#     ports:
#       - "8080:8080"

#   worker:
#     build:
#       context: ./worker
#     container_name: webhookhub-worker
#     env_file:
#       - .env
#     depends_on:
#       postgres:
#         condition: service_healthy
#       kafka:
#         condition: service_healthy
#       redis:
#         condition: service_started
#     restart: unless-stopped

# volumes:
#   pg_data:

services:
  postgres:
    image: postgres:15
    container_name: webhookhub-postgres
    environment:
      POSTGRES_USER: webhookhub
      POSTGRES_PASSWORD: webhookhub
      POSTGRES_DB: webhookhub
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U webhookhub" ]
      interval: 5s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: webhookhub-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: webhookhub-kafka
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7
    container_name: webhookhub-redis
    ports:
      - "6379:6379"

  db-migrate:
    build:
      context: ./db
    container_name: webhookhub-db-migrate
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started

  api:
    build:
      context: ./api
    container_name: webhookhub-api
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      db-migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    restart: unless-stopped

  worker:
    build:
      context: ./worker
    container_name: webhookhub-worker
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      db-migrate:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  pg_data:
